project: IngenicoConnectKit.xcodeproj
schemes:
- IngenicoConnectKit
targets:
- IngenicoConnectKit
- IngenicoConnectKitTests
clean_build: true
retain_public: true
build_arguments:
- -destination
- platform="iOS Simulator,name=iPhone 13,OS=15.5"
